[package]
name = "rust_animal"
version = "0.1.0"
authors = ["tugajin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
derive_more = "*"
rand = "*"